import { COUNTRY_NAMES } from "./countries";

/**
 * Major cities (and climbing hubs) keyed by the display names in `COUNTRY_NAMES`.
 * Merged at runtime with catalog / user gym cities so known locations always appear.
 */
const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Singapore: ["Singapore"],
  Japan: [
    "Tokyo",
    "Osaka",
    "Kyoto",
    "Yokohama",
    "Nagoya",
    "Fukuoka",
    "Sapporo",
    "Kobe",
    "Sendai",
    "Hiroshima",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Ulsan",
    "Suwon",
  ],
  Taiwan: ["Taipei", "New Taipei", "Taichung", "Kaohsiung", "Tainan", "Hsinchu"],
  "Hong Kong": ["Hong Kong"],
  China: [
    "Shanghai",
    "Beijing",
    "Shenzhen",
    "Guangzhou",
    "Chengdu",
    "Hangzhou",
    "Chongqing",
    "Wuhan",
    "Xi'an",
    "Nanjing",
    "Suzhou",
    "Tianjin",
  ],
  Malaysia: [
    "Kuala Lumpur",
    "Petaling Jaya",
    "Shah Alam",
    "Subang Jaya",
    "Penang",
    "Johor Bahru",
    "Ipoh",
    "Malacca",
    "Kota Kinabalu",
    "Kuching",
  ],
  Thailand: [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Hat Yai",
    "Khon Kaen",
    "Nonthaburi",
    "Nakhon Ratchasima",
  ],
  Indonesia: [
    "Jakarta",
    "Bandung",
    "Surabaya",
    "Bali",
    "Yogyakarta",
    "Medan",
    "Makassar",
    "Semarang",
    "Tangerang",
    "Depok",
    "Bekasi",
  ],
  Vietnam: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Nha Trang",
    "Hue",
  ],
  Philippines: [
    "Manila",
    "Quezon City",
    "Makati",
    "Cebu City",
    "Davao City",
    "Taguig",
    "Pasig",
  ],
  India: [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Chandigarh",
  ],
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
    "Gold Coast",
    "Hobart",
    "Darwin",
    "Newcastle",
  ],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Dunedin",
    "Queenstown",
  ],
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Seattle",
    "Denver",
    "Boston",
    "Portland",
    "San Francisco",
    "Las Vegas",
    "Miami",
    "Atlanta",
    "Washington",
    "Boulder",
    "Salt Lake City",
  ],
  Canada: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Ottawa",
    "Edmonton",
    "Winnipeg",
    "Quebec City",
    "Victoria",
    "Halifax",
  ],
  Mexico: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Cancún",
    "Tijuana",
    "Puebla",
    "Mérida",
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Glasgow",
    "Bristol",
    "Leeds",
    "Liverpool",
    "Sheffield",
    "Cardiff",
    "Belfast",
    "Oxford",
    "Cambridge",
  ],
  Ireland: ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
  France: [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Bordeaux",
    "Lille",
    "Strasbourg",
    "Grenoble",
  ],
  Germany: [
    "Berlin",
    "Munich",
    "Hamburg",
    "Frankfurt",
    "Cologne",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dresden",
    "Nuremberg",
  ],
  Italy: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Florence",
    "Bologna",
    "Venice",
    "Genoa",
    "Verona",
    "Palermo",
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Bilbao",
    "Málaga",
    "Zaragoza",
    "Granada",
  ],
  Portugal: ["Lisbon", "Porto", "Braga", "Coimbra", "Faro"],
  Netherlands: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
  ],
  Belgium: ["Brussels", "Antwerp", "Ghent", "Bruges", "Leuven", "Liège"],
  Switzerland: [
    "Zurich",
    "Geneva",
    "Basel",
    "Bern",
    "Lausanne",
    "Lucerne",
    "Interlaken",
  ],
  Austria: ["Vienna", "Salzburg", "Innsbruck", "Graz", "Linz"],
  Norway: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Umeå"],
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  Finland: ["Helsinki", "Espoo", "Tampere", "Turku", "Oulu"],
  Iceland: ["Reykjavík", "Akureyri"],
  Poland: ["Warsaw", "Kraków", "Wrocław", "Gdańsk", "Poznań", "Łódź"],
  Czechia: ["Prague", "Brno", "Ostrava", "Plzeň"],
  Greece: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
  Croatia: ["Zagreb", "Split", "Dubrovnik", "Rijeka", "Zadar"],
  Slovenia: ["Ljubljana", "Maribor", "Kranj"],
  "South Africa": [
    "Cape Town",
    "Johannesburg",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
  ],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Belo Horizonte",
    "Curitiba",
    "Porto Alegre",
    "Salvador",
  ],
  Argentina: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Bariloche"],
  Chile: ["Santiago", "Valparaíso", "Concepción", "Viña del Mar"],
};

function uniqueSorted(values: string[]): string[] {
  const seen = new Set<string>();
  const ordered: string[] = [];
  for (const value of values) {
    const trimmed = value.trim();
    if (!trimmed) continue;
    const key = trimmed.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    ordered.push(trimmed);
  }
  return ordered.sort((a, b) => a.localeCompare(b));
}

/** Canonical country name → city list for dropdowns. */
export function citiesForCountry(
  country: string,
  extras: string[] = [],
): string[] {
  const key = country.trim();
  const base =
    CITIES_BY_COUNTRY[key] ??
    CITIES_BY_COUNTRY[
      COUNTRY_NAMES.find((name) => name.toLowerCase() === key.toLowerCase()) ?? ""
    ] ??
    [];
  return uniqueSorted([...base, ...extras]);
}
