import { countryMeta } from "./countries";

/**
 * Major cities (and climbing hubs) keyed by ISO 3166-1 Alpha-2 codes.
 * Merged at runtime with catalog / user gym cities so known locations always appear.
 */
const CITIES_BY_ISO2: Record<string, string[]> = {
  SG: ["Singapore"],
  JP: [
    "Tokyo",
    "Osaka",
    "Kyoto",
    "Yokohama",
    "Nagoya",
    "Fukuoka",
    "Sapporo",
    "Kobe",
    "Sendai",
    "Hiroshima",
  ],
  KR: [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Ulsan",
    "Suwon",
  ],
  TW: ["Taipei", "New Taipei", "Taichung", "Kaohsiung", "Tainan", "Hsinchu"],
  HK: ["Hong Kong"],
  CN: [
    "Shanghai",
    "Beijing",
    "Shenzhen",
    "Guangzhou",
    "Chengdu",
    "Hangzhou",
    "Chongqing",
    "Wuhan",
    "Xi'an",
    "Nanjing",
    "Suzhou",
    "Tianjin",
  ],
  MY: [
    "Kuala Lumpur",
    "Petaling Jaya",
    "Shah Alam",
    "Subang Jaya",
    "Penang",
    "Johor Bahru",
    "Ipoh",
    "Malacca",
    "Kota Kinabalu",
    "Kuching",
  ],
  TH: [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Hat Yai",
    "Khon Kaen",
    "Nonthaburi",
    "Nakhon Ratchasima",
  ],
  ID: [
    "Jakarta",
    "Bandung",
    "Surabaya",
    "Bali",
    "Yogyakarta",
    "Medan",
    "Makassar",
    "Semarang",
    "Tangerang",
    "Depok",
    "Bekasi",
  ],
  VN: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Nha Trang",
    "Hue",
  ],
  PH: [
    "Manila",
    "Quezon City",
    "Makati",
    "Cebu City",
    "Davao City",
    "Taguig",
    "Pasig",
  ],
  IN: [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Chandigarh",
  ],
  AU: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
    "Gold Coast",
    "Hobart",
    "Darwin",
    "Newcastle",
  ],
  NZ: [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Dunedin",
    "Queenstown",
  ],
  US: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Seattle",
    "Denver",
    "Boston",
    "Portland",
    "San Francisco",
    "Las Vegas",
    "Miami",
    "Atlanta",
    "Washington",
    "Boulder",
    "Salt Lake City",
  ],
  CA: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Ottawa",
    "Edmonton",
    "Winnipeg",
    "Quebec City",
    "Victoria",
    "Halifax",
  ],
  MX: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Cancún",
    "Tijuana",
    "Puebla",
    "Mérida",
  ],
  GB: [
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Glasgow",
    "Bristol",
    "Leeds",
    "Liverpool",
    "Sheffield",
    "Cardiff",
    "Belfast",
    "Oxford",
    "Cambridge",
  ],
  IE: ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
  FR: [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Bordeaux",
    "Lille",
    "Strasbourg",
    "Grenoble",
  ],
  DE: [
    "Berlin",
    "Munich",
    "Hamburg",
    "Frankfurt",
    "Cologne",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dresden",
    "Nuremberg",
  ],
  IT: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Florence",
    "Bologna",
    "Venice",
    "Genoa",
    "Verona",
    "Palermo",
  ],
  ES: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Bilbao",
    "Málaga",
    "Zaragoza",
    "Granada",
  ],
  PT: ["Lisbon", "Porto", "Braga", "Coimbra", "Faro"],
  NL: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
  ],
  BE: ["Brussels", "Antwerp", "Ghent", "Bruges", "Leuven", "Liège"],
  CH: [
    "Zurich",
    "Geneva",
    "Basel",
    "Bern",
    "Lausanne",
    "Lucerne",
    "Interlaken",
  ],
  AT: ["Vienna", "Salzburg", "Innsbruck", "Graz", "Linz"],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø"],
  SE: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Umeå"],
  DK: ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  FI: ["Helsinki", "Espoo", "Tampere", "Turku", "Oulu"],
  IS: ["Reykjavík", "Akureyri"],
  PL: ["Warsaw", "Kraków", "Wrocław", "Gdańsk", "Poznań", "Łódź"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzeň"],
  GR: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
  HR: ["Zagreb", "Split", "Dubrovnik", "Rijeka", "Zadar"],
  SI: ["Ljubljana", "Maribor", "Kranj"],
  ZA: [
    "Cape Town",
    "Johannesburg",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
  ],
  AE: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
  BR: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Belo Horizonte",
    "Curitiba",
    "Porto Alegre",
    "Salvador",
  ],
  AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Bariloche"],
  CL: ["Santiago", "Valparaíso", "Concepción", "Viña del Mar"],
};

function uniqueSorted(values: string[]): string[] {
  const seen = new Set<string>();
  const ordered: string[] = [];
  for (const value of values) {
    const trimmed = value.trim();
    if (!trimmed) continue;
    const key = trimmed.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    ordered.push(trimmed);
  }
  return ordered.sort((a, b) => a.localeCompare(b));
}

/** Resolve cities for a country name, alias, or ISO code. */
export function citiesForCountry(
  country: string,
  extras: string[] = [],
): string[] {
  const meta = countryMeta(country);
  const base = meta.iso2 ? (CITIES_BY_ISO2[meta.iso2] ?? []) : [];
  return uniqueSorted([...base, ...extras]);
}
